files:
  include: 'src/assets/**/*.s+(a|c)ss'
  ignore:
    - 'src/assets/stylesheets/libs/**/*.scss'
    - 'src/assets/stylesheets/application.scss'

options:
  formatter: stylish
  merge-default-rules: false

rules:
  # Extends
  extends-before-mixins: 1
  extends-before-declarations: 1
  placeholder-in-extend: 1

  # Mixins
  mixins-before-declarations: 1

  # Line Spacing
  one-declaration-per-line: 1
  empty-line-between-blocks: 1
  single-line-per-selector: 1

  # Disallows
  no-attribute-selectors: 0
  no-color-hex: 0
  no-color-keywords: 1
  no-color-literals:
    - 1
    - allow-rgba: true
  no-combinators: 1
  no-css-comments: 1
  no-debug: 1
  no-disallowed-properties: 0
  no-duplicate-properties: 1
  no-empty-rulesets: 1
  no-extends: 1
  no-ids: 1
  no-important: 1
  no-invalid-hex: 1
  no-mergeable-selectors: 1
  no-misspelled-properties: 1
  no-qualifying-elements: 1
  no-trailing-whitespace: 1
  no-trailing-zero: 1
  no-transition-all: 1
  no-universal-selectors: 0
  no-warn: 1
  property-units: 0

  # No Vendor Prefixes
  no-vendor-prefixes:
    - 1
    - ignore-non-standard: true

  # Style Guide
  attribute-quotes:
    - 1
    - include: true
  bem-depth:
    - 1
    - max-depth: 1
  border-zero: 1
  brace-style:
    - 1
    - style: '1tbs'
    - allow-single-line: false
  clean-import-paths: 1
  empty-args:
    - 1
    - include: false
  hex-length:
    - 1
    - style: short
  hex-notation:
    - 1
    - style: lowercase
  indentation:
    - 1
    - size: 2
  leading-zero:
    - 1
    - include: true

  max-line-length:
    - 1
    - length: 80
  nesting-depth:
    - 1
    - max-depth: 3
  property-sort-order: 1
  pseudo-element: 1
  quotes:
    - 1
    - style: double
  shorthand-values: 1
  url-quotes: 1
  variable-for-property: 1
  zero-unit: 1

  # Inner Spacing
  space-after-comma: 1
  space-before-colon: 1
  space-after-colon: 1
  space-before-brace: 1
  space-before-bang: 1
  space-after-bang: 1
  space-between-parens: 1
  space-around-operator: 1

  # Name Formats
  function-name-format:
    - 1
    - allow-leading-underscore: true
    - convention: hyphenatedlowercase
  id-name-format: 0
  mixin-name-format: 1
  placeholder-name-format: 1
  variable-name-format: 1

  # Final Items
  trailing-semicolon: 2
  final-newline: 1
